/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework:spring-context:6.2.2")
    
    implementation("com.opencsv:opencsv:5.9")
    
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = "ru.bsuedu.cad.lab.Main"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}